version: 2.1

orbs:
  python: circleci/python@0.2.1

executors:
  ubuntu-small:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: small

commands:
  prepare_env:
    steps:
      - run:
            command: |  # use pipenv to install dependencies
              curl -o conda.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
              sh conda.sh -b
              source $HOME/miniconda3/bin/activate
              pip install -U pytest 
  test_file:
    parameters:
      file_path:
        default: tests/test_math.py
        type: string
        
    steps:
      - run: pytest <<parameters.file_path>>
    
jobs:
  test_operation:
    executor: ubuntu-small
    parallelism: 2
    steps:
      - checkout
      - prepare_env
      - test_file:
          file_path: tests/test_math.py

 
workflows:
  main:
    jobs: 
      - test_operation
