version: 2.1

orbs:
  python: circleci/python@0.2.1

executors:
  ubuntu-small:
    machine:
      image: ubuntu-1604:201903-01
    resource_class: small

commands:
  test_func_in_math_file:
    parameters:
      func_name:
        default: "yo"
        type: string
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            curl -o conda.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
            sh conda.sh -b
            source $HOME/miniconda3/bin/activate
            pip install -U pytest 
            pytest tests/test_math.py -k <<parameters.func_name>>
    
jobs:
  test_add:
    executor: ubuntu-small
    steps:
      - test_func_in_math_file:
          func_name: "test_add"
      
  test_minus:
    executor: ubuntu-small
    steps:
      - test_func_in_math_file:
          func_name: "test_minus"

 
workflows:
  main:
    jobs: 
      - test_add
      - test_minus
